### ISSUE TITLE
flatbuffer gen shell scripts for macOS

### ISSUE THREAD

**Issue by sekkit** [xieliujian/UnityFramework#1]
```
#!/bin/bash

# 指定起始文件夹

SRCDIR="../../Msg/flatbuffer/"
CSHARP_C_DSTDIR="../../Client/client/Assets/Scripts/Msg/"
LUA_C_DSTDIR="../../Client/client/Assets/StreamingAssets/lua/msg/"
LUA_S_DSTDIR="../../Server/skynet-1.2.0/game/msg/"
LUA_PREFIX="3rd."

LUA_C_DSTDIR_FROM_CSHARP_C_DSTDIR="../../StreamingAssets/lua/msg/"
LUA_S_DSTDIR_FROM_LUA_C_DSTDIR="../../../../../../Server/skynet-1.2.0/game/msg/"

echo "--------------------------------------------------------------------------"
echo "SrcDir"
echo $SRCDIR

echo "CSHARP_C_DSTDIR"
echo $CSHARP_C_DSTDIR

echo "Lua_Client_DstDir"
echo $LUA_C_DSTDIR

echo "Lua_Server_DstDir"
echo $LUA_S_DSTDIR

echo "--------------------------------------------------------------------------"
echo "delete CSHARP_C_DSTDIR"
rm -rf $CSHARP_C_DSTDIR

echo "delete LUA_C_DSTDIR"
rm -rf $LUA_C_DSTDIR

echo "delete LUA_S_DSTDIR"
rm -rf $LUA_S_DSTDIR

# 参数 /R 表示需要遍历子文件夹,去掉表示不遍历子文件夹

# %%f 是一个变量,类似于迭代器,但是这个变量只能由一个字母组成,前面带上%%

# 括号中是通配符,可以指定后缀名,*.*表示所有文件

echo "--------------------------------------------------------------------------"
FILES=$SRCDIR*
for f in $FILES
do
    echo "Processing $f file..."
    # take action on each file. $f store current file name
    ./flatc --csharp -o $CSHARP_C_DSTDIR $f
    ./flatc --lua -o $LUA_C_DSTDIR --lua-prefix $LUA_PREFIX $f
    ./flatc --lua -o $LUA_S_DSTDIR $f
done 

I mod it to run in MacOS

**Comment by sekkit** [comment]
#!/bin/bash

# 指定起始文件夹

SRCDIR="../../Msg/flatbuffer/"
CSHARP_C_DSTDIR="../../Client/client/Assets/Scripts/Msg/"
LUA_C_DSTDIR="../../Client/client/Assets/StreamingAssets/lua/msg/"
LUA_S_DSTDIR="../../Server/skynet-1.2.0/game/msg/"
LUA_PREFIX="3rd."

LUA_C_DSTDIR_FROM_CSHARP_C_DSTDIR="../../StreamingAssets/lua/msg/"
LUA_S_DSTDIR_FROM_LUA_C_DSTDIR="../../../../../../Server/skynet-1.2.0/game/msg/"

echo "--------------------------------------------------------------------------"
echo "SrcDir"
echo $SRCDIR

echo "CSHARP_C_DSTDIR"
echo $CSHARP_C_DSTDIR

echo "Lua_Client_DstDir"
echo $LUA_C_DSTDIR

echo "Lua_Server_DstDir"
echo $LUA_S_DSTDIR

echo "--------------------------------------------------------------------------"
echo "delete CSHARP_C_DSTDIR"
rm -rf $CSHARP_C_DSTDIR

echo "delete LUA_C_DSTDIR"
rm -rf $LUA_C_DSTDIR

echo "delete LUA_S_DSTDIR"
rm -rf $LUA_S_DSTDIR

# 参数 /R 表示需要遍历子文件夹,去掉表示不遍历子文件夹

# %%f 是一个变量,类似于迭代器,但是这个变量只能由一个字母组成,前面带上%%

# 括号中是通配符,可以指定后缀名,*.*表示所有文件

echo "--------------------------------------------------------------------------"
FILES=$SRCDIR*
for f in $FILES
do
    echo "Processing $f file..."
    # take action on each file. $f store current file name
    ./flatc --csharp -o $CSHARP_C_DSTDIR $f
    ./flatc --lua -o $LUA_C_DSTDIR --lua-prefix $LUA_PREFIX $f
    ./flatc --lua -o $LUA_S_DSTDIR $f
done 

I mod it to run in MacOS

**Comment by xieliujian** [comment]
windows下开发可以不用shell
